project/apps/Home/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

from . import views

from .views import home

app_name = "Home"

urlpatterns = [
    path("", views.home, name="home"),
    path('login/', views.login_request, name="login"),
    path('logout/', LogoutView.as_view(template_name="Home/logout.html"), name="logout"),
    path('about/', TemplateView.as_view(template_name="Home/about.html"), name="about"),
    path('register/', views.register, name="register"),

]

urlpatterns += staticfiles_urlpatterns()

project/apps/cliente/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "cliente"

urlpatterns = [
    path("", home, name="home"),
    path('registrarformulario/', FormularioClienteViews.index, name='registrarFormulario'),
    path('guardarformulario/', FormularioClienteViews.proscesarform, name='guardarformulario'),
    path("cliente/delete/<int:pk>", views.Clientedelete.as_view(), name="cliente_delete"),
]

project/apps/producto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *
from . import views
from django.contrib.auth.decorators import login_required



app_name = "producto"

urlpatterns = [
    path('', home, name='home'),
    path("producto/list/", views.Productolist.as_view(), name="producto_list"),
    path("producto/create/", views.Productocreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", views.Productodetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", views.Productoupdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", views.Productodelete.as_view(), name="producto_delete"),
    #url(r'^workers/$', login_required( views.RootWorkerView.as_view())),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path("cliente/", include('cliente.urls')),
    path('producto/', include('producto.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/Home/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ["username", "password"]
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control"}),
        }


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        # Quita los mensajes de ayuda
        # help_texts = {k: "" for k in fields}
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "password1": forms.PasswordInput(attrs={"class": "form-control"}),
            "password2": forms.PasswordInput(attrs={"class": "form-control"}),
            }     

project/apps/Home/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse
from django.http.request import HttpRequest
from django.shortcuts import render

from . import forms

# Create your views here.

def home(request):
    return render(request, "Home/index.html")

#! LOGIN

def login_request(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get("username")
            contraseña = form.cleaned_data.get("password")
            user = authenticate(username=usuario, password=contraseña)
            if user is not None:
                login(request, user)
                return render(request, "Home/index.html", {"mensaje": "Inició sesión correctamente"})
    else:
        form = forms.CustomAuthenticationForm()
    return render(request, "Home/login.html", {"form": form})


#! REGISTRO

@staff_member_required
def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            form.save()
            return render(request, "Home/index.html", {"mensaje": "Vendedor creado "})
    else:
        form = forms.CustomUserCreationForm()
    return render(request, "Home/register.html", {"form": form})

project/apps/Home/templates/Home/about.html
{% extends 'Home/base.html' %}
    {% load static %}
        
    {% block INDEX_TITULO %} <h1>Santiago Avalos</h1> {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}
    <div class="block-about">
        <img src="{% static 'Home/assets/img/FotoPerfil2.jpg' %}" alt="imagen">
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Porro tempore quas nulla aperiam culpa dolore repellat tempora amet sint eius, dolorem fugit ipsum quibusdam repellendus similique sequi officia nesciunt rem? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Qui, mollitia. Accusamus, repudiandae deserunt eligendi iusto, harum expedita et, numquam id inventore eveniet beatae dicta voluptatem cum suscipit ipsam ab Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum, illum blanditiis. Commodi repudiandae qui ea molestiae alias, autem laborum non cupiditate dolorem! Deleniti saepe dignissimos harum autem accusantium dolor ad. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iusto officia non neque placeat reiciendis voluptatem saepe atque minima eius, repellat harum quae repellendus! Repellendus, repellat ipsam. Exercitationem facere quasi a.</p>
    </div>
        <div class="enlaces">
            <a href="#" class="btn btn-light btn-lg">Instagram</a>
            <a href="#" class="btn btn-success btn-lg">Whatsapp</a>
        </div>
    {% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="Joaquín Mazza" />
        <title>ATodaMaquina</title>
        <link rel="icon" type="image/x-icon" href="{% static 'Home/assets/img/icono.png' %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'Home/css/styles.css' %}"/>
        <link rel="stylesheet" href="{% static 'Home/css/normalize.css' %}"/>
    </head>
    <body>
        <!-- Encabezado -->
        {% include 'Home/header.html' %}

        <!-- Navegacion -->
        {% include 'Home/navbar.html' %}
        <div class="fullscreen">
            {% block BASE_CONTENIDO %}
                {% block INDEX_TITULO %}{% endblock INDEX_TITULO %}
                {% block INDEX_CONTENIDO %}{% endblock INDEX_CONTENIDO %}
            {% endblock BASE_CONTENIDO %}
            

            <!-- Pie de Pagina -->
            {% include 'Home/footer.html' %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

project/apps/Home/templates/Home/footer.html
<footer class="footer">
    <p>Todos los derechos reservados</p>
    <p>Desing: Joaquín Mazza</p>
</footer>

project/apps/Home/templates/Home/header.html
{% load static %}

<header>
    <div class="logo">
    <a href="{% url 'Home:home' %}">
        <img src="{% static 'Home/assets/img/icono.png' %}" alt="Logo">
    </a>
    </div>
</header>

project/apps/Home/templates/Home/index.html
{% extends 'Home/base.html' %}
    {% load static %}

    {% block BASE_CONTENIDO %}
        {% block INDEX_TITULO %} <h1>Home</h1> {% endblock INDEX_TITULO %}
        {% block INDEX_CONTENIDO %}

            {% if user.is_authenticated %}
                {{ mensaje }}
                <h3> Bienvenido {{ user.username }}</h3>
            {% endif %}

            {% if user.is_staff %}
                <div class="enlaces">
                    <a href="{% url 'admin:index' %}" class="btn btn-outline-dark">Panel de Administración</a>
                    <a href="{% url 'Home:register' %}" class="btn btn-outline-dark">Registrar nuevo vendedor</a>
                </div>
            {% endif %}

            
            <section class="block-home">
                <h2>Les presento algunos de los cambios que logramos</h2>
                <article>
                    <div>
                        <img src="{% static 'Home/assets/img/1AsesoradoFrente.jpg' %}" alt="">
                        <img src="{% static 'Home/assets/img/1AsesoradoEspalda.jpg' %}" alt="">
                    </div>
                    <p class="texto-home">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer commodo, nulla eu rutrum mattis, justo massa fermentum nisi, et malesuada mi mi a tortor. Fusce consectetur eros sed urna blandit, in posuere nisl pellentesque. Cras elit sem, volutpat id neque eu, tincidunt iaculis magna. Sed nec enim arcu. Duis in massa nec sapien mollis rutrum. Phasellus sit amet lobortis nisi. Phasellus eget arcu a nisi ullamcorper ultricies. Praesent gravida orci eget hendrerit sollicitudin.</p>
                </article>
                    
                <article>
                    <div>
                        <img src="{% static 'Home/assets/img/2AsesoradoFrente.jpg' %}" alt="">
                        <img src="{% static 'Home/assets/img/2AsesoradoEspalda.jpg' %}" alt="">
                    </div>
                    <p class="texto-home">Nam laoreet sem non metus viverra mollis. Maecenas diam tortor, bibendum quis augue non, hendrerit ornare mauris. Aliquam et blandit eros. Nam ut auctor ante. Fusce vitae interdum metus, sed tincidunt dolor. Suspendisse quis mattis elit. Sed pretium ac leo at tincidunt. Mauris posuere turpis ante, et dignissim ligula congue at.</p>
                </article>
            </section>
        {% endblock INDEX_CONTENIDO %}
    {% endblock BASE_CONTENIDO %}

project/apps/Home/templates/Home/login.html
{% extends 'Home/index.html' %}

    {% block INDEX_TITULO %} <h1>Login</h1> {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}

        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="d-grid gap-3"> 
                <button type="submit" class="btn btn-success enlaces">Iniciar sesión</button>
            </div>
        </form>

    {% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/logout.html
{% extends 'Home/index.html' %}

    {% block INDEX_CONTENIDO %}
        <div class="fs-3 fst-italic ">
            <p>Has cerrado sesión</p>
        </div>
    {% endblock INDEX_CONTENIDO %}

project/apps/Home/templates/Home/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item order-first">
            <a class="nav-link {% if request.path == "/home/" %} active  {% endif %}" aria-current="page" href="{% url 'Home:home' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == "/about/" %} active  {% endif %}" href="{% url 'Home:about' %}">Sobre Mi</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == "/cliente/" %} active  {% endif %}" href="{% url 'cliente:registrarFormulario' %}">Contactanos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == "/producto/" %} active  {% endif %}" href="{% url 'producto:home' %}">Asesorias</a>
          </li>
          {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == "/cliente/" %} active  {% endif %}" href="{% url 'cliente:home' %}">Información</a>
            </li>
          {% endif %}
          {% if user.is_authenticated %}
            <li class="nav-item order-last">
              <a class="nav-link" href="{% url 'Home:logout' %}">Cerrar Sesión</a>
            </li>
          {% endif %}
          {% if not user.is_authenticated %}
            <li class="nav-item order-last">
              <a class="nav-link {% if request.path == "/login/" %} active  {% endif %}" href="{% url 'Home:login' %}">Login</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

project/apps/Home/templates/Home/register.html
{% extends 'Home/base.html' %}

    {% block INDEX_TITULO %} <h1>Registro de usuario</h1> {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}

        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="enlaces"> 
                <button type="submit" class="btn btn-success">Registrar nuevo usuario</button>
            </div>
        </form>

    {% endblock INDEX_CONTENIDO %}