project/apps/producto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import *
from . import views
from django.contrib.auth.decorators import login_required



app_name = "producto"

urlpatterns = [
    path('', home, name='home'),
    path("producto/list/", views.Productolist.as_view(), name="producto_list"),
    path("producto/create/", views.Productocreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", views.Productodetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", views.Productoupdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", views.Productodelete.as_view(), name="producto_delete"),
    #url(r'^workers/$', login_required( views.RootWorkerView.as_view())),
]   

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path("cliente/", include('cliente.urls')),
    path('producto/', include('producto.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/producto/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descripcion = models.CharField(max_length=250, null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(default=timezone.now, editable=False, verbose_name='fecha de actualizacion')
    imagen = models.ImageField(upload_to='productos', blank=True, null=True)

    def __str__(self):
        return self.nombre

project/apps/producto/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        exclude = ['fecha_actualizacion']
        fields = ('nombre', 'precio', 'descripcion', 'imagen')

project/apps/producto/views.py
from typing import Any
from .models import Producto
from django.contrib.auth.decorators import login_required

#! importaciones para login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models

def home(request):
    productos_registros = Producto.objects.all()
    contexto = {"productos": productos_registros}
    return render(request, "producto/index.html", contexto)

#Producto


#List
class Productolist(LoginRequiredMixin, ListView):
    model = models.Producto
    login_url = '../../../login'
    redirect_field_name = 'redirect_to'

    def get_queryset(self) -> QuerySet[Any]:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Producto.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Producto.objects.all()
        return object_list

#Create
class Productocreate(LoginRequiredMixin, CreateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy('producto:producto_list')
    login_url = '../../../login'
    redirect_field_name = 'redirect_to'

#Detail
class Productodetail(LoginRequiredMixin, DetailView):
    model = models.Producto
    login_url = '../../../login'
    redirect_field_name = 'redirect_to'

#Update
class Productoupdate(LoginRequiredMixin, UpdateView):
    model = models.Producto
    login_url = '../../../login'
    redirect_field_name = 'redirect_to'
    form_class = forms.ProductoForm
    success_url = reverse_lazy('producto:producto_list')

#Delete
class Productodelete(LoginRequiredMixin, DeleteView):
    model = models.Producto
    login_url = '../../../login'
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('producto:producto_list')

project/apps/producto/templates/producto/index.html
{% extends 'Home/base.html' %}
    {% load static %}

    {% block INDEX_TITULO %} <h1>Asesorias</h1> {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}
        {% if user.is_authenticated %}
        <div class="enlaces">
            <a href="{% url 'producto:producto_create' %}" type="button" class="btn btn-primary">Crear Asesoria</a><br>
            <a href="{% url 'producto:producto_list' %}" type="button" class="btn btn-primary">Listar Asesoria</a><br>
        </div>
        {% endif %}

        <section class="imagen-producto muestra">
            {% for producto in productos %}
                <article>
                    <p>{{ producto.nombre }}</p>
                    <p>{{ producto.precio }}</p>
                    <p>{{ producto.descripcion }}</p>
                    {% if producto.imagen %}
                        <div class="imagen-producto">
                            <img src="{{ producto.imagen.url }}" alt="imagen">
                        </div>
                    {% else %}
                        <div class="">
                            <img src="{% static 'producto/blanco.jpg' %}" alt="imagen">
                        </div>
                    {% endif %}
                    <a href="#" type="button" class="btn btn-outline-primary btn-lg enlaces">Comprar</a>
                </article>
            {% endfor %}
        </section>

    {% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_confirm_delete.html
{% extends 'Home/base.html' %}

    {% block INDEX_CONTENIDO %}
        <h1>Eliminar de Asesorias</h1>

        <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object }}"?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirmar</button>
        </form>
    {% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_detail.html
{% extends 'Home/base.html' %}

    {% block INDEX_TITULO %} <h1>Detalle de Asesorias</h1> {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}
        
        <ul>
            <li>Nombre: {{ object.nombre }} </li>
            <li>Precio: ${{ object.precio }} </li>
            <li>Descripción: {{ object.descripcion }} </li>
            <li>Imagen: {{ object.imagen }}</li>
            <li>Fecha de actualización: {{ object.fecha_actualizacion }} </li>
        </ul>
        
    {% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_form.html
{% extends 'Home/base.html' %}

    {% block INDEX_TITULO %} <h1>Crear/Actualizar Asesorias</h1> {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}
        
        <form class="formulario" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="enlaces" type="submit">Guardar</button>
        </form>

    {% endblock INDEX_CONTENIDO %}

project/apps/producto/templates/producto/producto_list.html
{% extends 'Home/base.html' %}

    {% block INDEX_CONTENIDO %}
        <div>
            <h1>Lista de Asesorias</h1>
            {% if object_list %}
            <div class="py-lg-4">
                <form action="{% url 'producto:producto_list' %}" method="get">
                    <input type="text" name="consulta" placeholder="Buscar...">
                </form>
            </div>

            {% for object in object_list %}
                <ul>
                    <li>{{ object.nombre }} ${{ object.precio }}
                        <a href="{% url 'producto:producto_detail' object.id %}" class="btn btn-secondary btn-lg">
                            Ver detalle</a>
                        <a href="{% url 'producto:producto_update' object.id %}" class="btn btn-primary  btn-lg">
                            Actualizar</a>
                        <a href="{% url 'producto:producto_delete' object.id %}" class="btn btn-danger  btn-lg">
                            Eliminar</a>
                    </li>
                </ul>
            {% endfor %}        
            {% else %}
                <p class="fs-4 fst-italic ">No hay registros ingresados</p>
            {% endif %}
        </div>
    {% endblock INDEX_CONTENIDO %} 
    