project/apps/cliente/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "cliente"

urlpatterns = [
    path("", home, name="home"),
    path('registrarformulario/', FormularioClienteViews.index, name='registrarFormulario'),
    path('guardarformulario/', FormularioClienteViews.proscesarform, name='guardarformulario'),
    path("cliente/delete/<int:pk>", views.Clientedelete.as_view(), name="cliente_delete"),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path("cliente/", include('cliente.urls')),
    path('producto/', include('producto.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/cliente/models.py
from django.db import models

# Create your models here.
class Sexo(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    sexo_id = models.ForeignKey(Sexo, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

project/apps/cliente/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'
        widgets = {'nacimiento': forms.DateInput(attrs={'type': 'date'})}

project/apps/cliente/views.py
from datetime import date
from django.views.generic import DeleteView
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.contrib.admin.views.decorators import staff_member_required

from .forms import ClienteForm
from . import models

# Create your views here.
from .models import Cliente, Sexo

@staff_member_required
def home(request):
    clientes_registros = Cliente.objects.all()
    contexto = {"clientes": clientes_registros}
    return render(request, "cliente/index.html", contexto)



class FormularioClienteViews(HttpRequest):

    def index(request):
        cliente = ClienteForm()
        return render(request, 'cliente/formulario.html', {'form': cliente})
    
    def proscesarform(request):
        cliente = ClienteForm(request.POST)
        if cliente.is_valid():
            cliente.save()
            cliente = ClienteForm()
            
        return render(request, 'cliente/formulario.html', {'form': cliente, 'mensaje': 'OK'})
    
#Delete
class Clientedelete(DeleteView):
    model = models.Cliente
    success_url = reverse_lazy('cliente:home')

project/apps/cliente/templates/cliente/cliente_confirm_delete.html
{% extends 'cliente/index.html' %}

    {% block INDEX_TITULO %} 
        <h1>Eliminación de clientes</h1>
    {% endblock INDEX_TITULO %}

    {% block INDEX_CONTENIDO %}

        <p class="fs-5 fst-italic">¿Confirma eliminar "{{ cliente }}"?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirmar</button>
        </form>


    {% endblock INDEX_CONTENIDO %}

project/apps/cliente/templates/cliente/formulario.html
{% extends 'Home/base.html' %}
    {% load crispy_forms_tags %}

    {% block INDEX_TITULO %} <h1>Formulario</h1> {% endblock INDEX_TITULO %}
    {% block INDEX_CONTENIDO %}

        {% if form.errors %}
            <div class="alerta">
                Hubo un error en la carga de Datos!
            </div> 
        {% endif %}

        <form class="formulario" action="{% url 'cliente:guardarformulario' %}" method="POST">
            {% csrf_token %}
            {% if mensaje %}
                <div class="alertaConcedida">
                    Mensaje Enviado Correctamente!
                </div>
            {% endif %}

            {{ form }}
            <button type="submit" class="boton">Enviar</button>
        </form>
        
    {% endblock INDEX_CONTENIDO %}

project/apps/cliente/templates/cliente/index.html
{% extends 'Home/base.html' %}

    {% block INDEX_CONTENIDO %}
        <h1>Clientes</h1>
        <div class="muestra">
            {% for cliente in clientes %}
            <div class="contenedor">           
                <p>{{ cliente.nombre }}</p>
                <p>{{ cliente.apellido }}</p>
                <p>{{ cliente.nacimiento }}</p>
                <p>{{ cliente.sexo_id }}</p>
                <a href="{% url 'cliente:cliente_delete' cliente.id %}" class="btn btn-danger btn-lg">Eliminar</a>
            </div>
        {% endfor %}
        </div>
    {% endblock INDEX_CONTENIDO %}